#!/usr/bin/env perl

use strict;
use warnings;
use JSON;
use Digest::SHA;
use File::Basename;
use Net::SCP;
use Carp;

my $file = $ARGV[0];
unless (defined $file) {
  croak("Usage: edl <file>");
}
my $userhome =  $ENV{'HOME'};

my $sha = Digest::SHA->new->addfile($file)->hexdigest;

my $jsonfile = "$userhome/.config/edl.json";
my $jsondata = do {
   open(my $json_fh, "<", $jsonfile)
      or die("Can't open \"$jsonfile\": $!\n");
   local $/;
   <$json_fh>
};
my $data = decode_json($jsondata);
my $weburl = $data->{weburl};
my $remotepath = $data->{remotepath};
my $server = $data->{server};

my $ext = (fileparse("$file", qr/\.[^.]*$/))[2];

my $scp = Net::SCP->new;
$scp->scp("$file", "$server:$remotepath/$sha$ext")
or die $scp->{errstr};

print "Your file is now at $weburl/$sha$ext\n";
